version: '2.1'

services:
  test-contract-provider:
    build:
      context: ./provider-back
      dockerfile: ./Dockerfile
    volumes:
      - ./provider-back/test:/app/test
      - ./.git:/app/.git
    environment:
      - PACT_BROKER_TOKEN
      - PACT_URL
      - CI
      - GITHUB_BRANCH
    command: npm run test:contract

  test-contract-consumer:
    build:
      context: ./consumer-front
      dockerfile: ./Dockerfile
    volumes:
      - ./consumer-front/test:/app/test
      - ./consumer-front/pacts:/app/pacts
      - ./consumer-front/logs:/app/logs
    command: npm run test:contract
