version: '3.8'

services:
  provider-test-contract:
    build:
      context: provider-clients-service
      dockerfile: Dockerfile
    command: npm run test:contract
    volumes:
      - ./provider-clients-service/test:/app/test
      - ./.git:/app/.git
    environment:
      - PACT_BROKER_TOKEN
      - PACT_URL
      - CI

  consumer-test-contract:
    build:
      context: consumer-frontend
      dockerfile: Dockerfile
    command: npm run test:contract
    volumes:
      - ./consumer-frontend/test:/app/test
      - ./consumer-frontend/pacts:/app/pacts
      - ./consumer-frontend/logs:/app/logs
