version: '2.1'

services:
# Serviços do Provider (sample-clientsService)
  base-provider:
    build:
      context: ./provider-clients-service
      dockerfile: ./Dockerfile

  provider-start:
    extends: base-provider
    command: npm start

  provider-test-contract:
    extends: base-provider
    command: npm run test:contract
    volumes:
      - ./provider-clients-service/test:/app/test
      - ./.git:/app/.git
    environment:
      - PACT_BROKER_TOKEN
      - PACT_URL
      - CI

# Serviços do Consumer (sample-Frontend)
  base-consumer:
    build:
      context: ./consumer-frontend
      dockerfile: ./Dockerfile

  consumer-start:
    extends: base-consumer
    command: npm start

  consumer-test-contract:
    extends: base-consumer
    command: npm run test:contract
    volumes:
      - ./consumer-frontend/test:/app/test
      - ./consumer-frontend/pacts:/app/pacts
      - ./consumer-frontend/logs:/app/logs
