name: Provider contract test performed via webhook

# https://docs.pact.io/pact_broker/overview/#webhooks

# When a new contract is published by the consumer (frontend) it was not executed
# with any version of the provider, so the pactflow runs a webhook that calls this
# pipeline and runs the provider contract test (clients-service), directly downloading
# the new contract (via 'pactUrl') and publishing the result to pactflow at the end.

# With this it is possible to guarantee that every new contract published is
# compatible or not with the version of the production provider.

# It is certain that the consumer will be executed on top of the production provider
# because I am checking out the default branch (main), which is where the production tags are.

on:
  repository_dispatch:
    types: [pact-changed]

jobs:
  test-contract:
    runs-on: ubuntu-18.04
    name: Run provider contract 

    steps:
    - name: Project checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.client_payload.providerProductionSha }}
    - run: docker-compose build provider-test-contract
    - name: Run provider contract test
      run: make provider-test-contract
      env:
        PACT_URL: ${{ github.event.client_payload.pactUrl }}
        PACT_BROKER_TOKEN: ${{ secrets.PACT_BROKER_TOKEN }}
