name: Teste de contrato do provider executado via webhook

# https://docs.pact.io/pact_broker/overview/#webhooks

# Quando um novo contrato é publicado pelo consumer (sample-Frontend) ele não foi executado
# com nenhuma versão do provider, com isso o pactflow executa webhook que chama essa pipeline
# e executa o teste de contrato do provider (sample-clientsService), baixando diretamente
# o novo contrato (através do 'pactUrl') e publicando o resultado no pactflow ao final.

# Com isso é possível garantir que todo novo contrato publicado é compatível ou não
# com a versão do provider de produção.

# É certo que será executado o consumer encima de provider de produção pois estou
# fazendo checkout da branch default (main), que é aonde estão as tags de produção.

on:
  repository_dispatch:
    types: [pact-changed]

jobs:
  test-contract:
    runs-on: ubuntu-18.04
    name: Run provider contract 

    steps:
    - name: Project checkout
      uses: actions/checkout@v2
    - run: docker-compose build test-contract-provider
    - name: Run provider contract test
      run: make test-contract-provider
      env:
        PACT_URL: ${{ github.event.client_payload.pactUrl }}
        PACT_BROKER_TOKEN: ${{ secrets.PACT_BROKER_TOKEN }}
